import type { CategorySchema } from '@/store/use-app-store';

export const categories: CategorySchema[] = [
  {
    id: 'wedding',
    slug: 'wedding',
    name: 'Toy',
    icon: 'Heart',
    description: 'Toy dəvət kartı',
    color: 'text-red-500',
    fields: [
      { key: 'brideName', label: 'Gəlin adı', type: 'text', required: true, placeholder: 'Gəlinin adı' },
      { key: 'groomName', label: 'Bəy adı', type: 'text', required: true, placeholder: 'Bəyin adı' },
      { key: 'date', label: 'Toy tarixi', type: 'date', required: true },
      { key: 'time', label: 'Başlama saatı', type: 'time', required: true },
      { key: 'location', label: 'Məkan', type: 'location', required: true, placeholder: 'Restoran / Zal adı' },
      { key: 'address', label: 'Ünvan', type: 'text', required: false, placeholder: 'Tam ünvan' },
      { key: 'phone', label: 'Əlaqə nömrəsi', type: 'phone', required: false, placeholder: '+994 XX XXX XX XX' },
      { key: 'guestCount', label: 'Qonaq sayı', type: 'number', required: false, placeholder: 'Təxmini qonaq sayı' },
    ],
  },
  {
    id: 'engagement',
    slug: 'engagement',
    name: 'Nişan',
    icon: 'Gem',
    description: 'Nişan dəvət kartı',
    color: 'text-pink-500',
    fields: [
      { key: 'brideName', label: 'Gəlin adı', type: 'text', required: true, placeholder: 'Gəlinin adı' },
      { key: 'groomName', label: 'Bəy adı', type: 'text', required: true, placeholder: 'Bəyin adı' },
      { key: 'date', label: 'Nişan tarixi', type: 'date', required: true },
      { key: 'time', label: 'Başlama saatı', type: 'time', required: true },
      { key: 'location', label: 'Məkan', type: 'location', required: true, placeholder: 'Məkan adı' },
      { key: 'phone', label: 'Əlaqə', type: 'phone', required: false },
    ],
  },
  {
    id: 'henna',
    slug: 'henna',
    name: 'Xına gecəsi',
    icon: 'Flower2',
    description: 'Xına gecəsi dəvəti',
    color: 'text-amber-500',
    fields: [
      { key: 'hostName', label: 'Ev sahibi', type: 'text', required: true, placeholder: 'Ev sahibinin adı' },
      { key: 'date', label: 'Tarix', type: 'date', required: true },
      { key: 'time', label: 'Saat', type: 'time', required: true },
      { key: 'location', label: 'Məkan', type: 'location', required: true },
      { key: 'address', label: 'Ünvan', type: 'text', required: false },
      { key: 'phone', label: 'Əlaqə', type: 'phone', required: false },
    ],
  },
  {
    id: 'birthday',
    slug: 'birthday',
    name: 'Ad günü',
    icon: 'Cake',
    description: 'Ad günü dəvət kartı',
    color: 'text-pink-500',
    fields: [
      { key: 'hostName', label: 'Ad günü sahibi', type: 'text', required: true, placeholder: 'Ad günü olan şəxs' },
      { key: 'age', label: 'Yaş', type: 'number', required: false, placeholder: 'Neçə yaş' },
      { key: 'date', label: 'Tarix', type: 'date', required: true },
      { key: 'time', label: 'Saat', type: 'time', required: true },
      { key: 'location', label: 'Məkan', type: 'location', required: true },
      { key: 'address', label: 'Ünvan', type: 'text', required: false },
      { key: 'phone', label: 'Əlaqə', type: 'phone', required: false },
    ],
  },
  {
    id: 'baby-shower',
    slug: 'baby-shower',
    name: 'Beşik toyu',
    icon: 'Baby',
    description: 'Beşik / körpə dəvəti',
    color: 'text-sky-500',
    fields: [
      { key: 'parentName', label: 'Valideyn adı', type: 'text', required: true, placeholder: 'Valideynin adı' },
      { key: 'babyName', label: 'Körpənin adı', type: 'text', required: false, placeholder: 'Körpənin adı (varsa)' },
      { key: 'date', label: 'Tarix', type: 'date', required: true },
      { key: 'time', label: 'Saat', type: 'time', required: true },
      { key: 'location', label: 'Məkan', type: 'location', required: true },
      { key: 'address', label: 'Ünvan', type: 'text', required: false },
      { key: 'phone', label: 'Əlaqə', type: 'phone', required: false },
    ],
  },
  {
    id: 'corporate',
    slug: 'corporate',
    name: 'Korporativ',
    icon: 'Briefcase',
    description: 'Şirkət tədbiri dəvəti',
    color: 'text-blue-500',
    fields: [
      { key: 'companyName', label: 'Şirkət adı', type: 'text', required: true, placeholder: 'Şirkətin adı' },
      { key: 'eventTitle', label: 'Tədbir adı', type: 'text', required: true, placeholder: 'Tədbirin adı' },
      { key: 'date', label: 'Tarix', type: 'date', required: true },
      { key: 'time', label: 'Saat', type: 'time', required: true },
      { key: 'location', label: 'Məkan', type: 'location', required: true },
      { key: 'address', label: 'Ünvan', type: 'text', required: false },
      { key: 'phone', label: 'Əlaqə', type: 'phone', required: false },
      { key: 'email', label: 'Email', type: 'email', required: false, placeholder: 'email@company.com' },
    ],
  },
  {
    id: 'masterclass',
    slug: 'masterclass',
    name: 'Master klass',
    icon: 'GraduationCap',
    description: 'Master klass dəvəti',
    color: 'text-purple-500',
    fields: [
      { key: 'instructor', label: 'Təlimçi adı', type: 'text', required: true, placeholder: 'Təlimçinin adı' },
      { key: 'topic', label: 'Mövzu', type: 'text', required: true, placeholder: 'Master klass mövzusu' },
      { key: 'date', label: 'Tarix', type: 'date', required: true },
      { key: 'time', label: 'Saat', type: 'time', required: true },
      { key: 'duration', label: 'Müddət (saat)', type: 'number', required: false, placeholder: '2' },
      { key: 'location', label: 'Məkan', type: 'location', required: true },
      { key: 'address', label: 'Ünvan', type: 'text', required: false },
      { key: 'price', label: 'Qiymət', type: 'text', required: false, placeholder: 'Pulsuz və ya qiymət' },
      { key: 'phone', label: 'Əlaqə', type: 'phone', required: false },
    ],
  },
  {
    id: 'seminar',
    slug: 'seminar',
    name: 'Seminar',
    icon: 'BookOpen',
    description: 'Seminar dəvət kartı',
    color: 'text-indigo-500',
    fields: [
      { key: 'speaker', label: 'Məruzəçi', type: 'text', required: true, placeholder: 'Məruzəçinin adı' },
      { key: 'topic', label: 'Mövzu', type: 'text', required: true, placeholder: 'Seminar mövzusu' },
      { key: 'date', label: 'Tarix', type: 'date', required: true },
      { key: 'time', label: 'Saat', type: 'time', required: true },
      { key: 'location', label: 'Məkan', type: 'location', required: true },
      { key: 'address', label: 'Ünvan', type: 'text', required: false },
      { key: 'phone', label: 'Əlaqə', type: 'phone', required: false },
      { key: 'email', label: 'Email', type: 'email', required: false },
    ],
  },
  {
    id: 'concert',
    slug: 'concert',
    name: 'Konsert',
    icon: 'Music',
    description: 'Konsert dəvəti',
    color: 'text-green-500',
    fields: [
      { key: 'artistName', label: 'Artist / Qrup adı', type: 'text', required: true, placeholder: 'Artist adı' },
      { key: 'date', label: 'Tarix', type: 'date', required: true },
      { key: 'time', label: 'Saat', type: 'time', required: true },
      { key: 'location', label: 'Məkan', type: 'location', required: true },
      { key: 'address', label: 'Ünvan', type: 'text', required: false },
      { key: 'price', label: 'Bilet qiyməti', type: 'text', required: false, placeholder: 'AZN' },
      { key: 'phone', label: 'Əlaqə', type: 'phone', required: false },
    ],
  },
  {
    id: 'general',
    slug: 'general',
    name: 'Ümumi tədbir',
    icon: 'PartyPopper',
    description: 'Ümumi tədbir dəvəti',
    color: 'text-orange-500',
    fields: [
      { key: 'eventTitle', label: 'Tədbir adı', type: 'text', required: true, placeholder: 'Tədbirin adı' },
      { key: 'hostName', label: 'Ev sahibi', type: 'text', required: true, placeholder: 'Ev sahibinin adı' },
      { key: 'date', label: 'Tarix', type: 'date', required: true },
      { key: 'time', label: 'Saat', type: 'time', required: true },
      { key: 'location', label: 'Məkan', type: 'location', required: true },
      { key: 'address', label: 'Ünvan', type: 'text', required: false },
      { key: 'description', label: 'Əlavə məlumat', type: 'textarea', required: false, placeholder: 'Ətraflı məlumat' },
      { key: 'phone', label: 'Əlaqə', type: 'phone', required: false },
    ],
  },
];
