import type { TemplateSchema } from '@/store/use-app-store';

const templates: Omit<TemplateSchema, 'preview'>[] = [
  {
    id: 'elegant-rose',
    category: 'wedding',
    name: 'Elegant Rose',
    slug: 'elegant-rose',
    description: 'Klassik və zərif toy dəvəti',
    thumbnail: '/templates/elegant-rose-thumb.png',
    background: 'linear-gradient(135deg, #fdf2f8 0%, #fce7f3 100%)',
    backgroundVariants: [
      'linear-gradient(135deg, #fdf2f8 0%, #fce7f3 100%)',
      'linear-gradient(135deg, #fff1f2 0%, #ffe4e6 100%)',
      'linear-gradient(135deg, #faf5ff 0%, #f3e8ff 100%)',
    ],
    colors: { primary: '#be185d', secondary: '#f43f5e', accent: '#fbcfe8' },
    font: 'Playfair Display',
    fonts: ['Playfair Display', 'Georgia', 'Lora'],
    layout: 'centered-card',
    positions: {
      title: { x: 50, y: 15, width: 80, height: 10, fontSize: 32, align: 'center', color: '#be185d' },
      couple: { x: 50, y: 30, width: 80, height: 8, fontSize: 24, align: 'center', color: '#1f2937' },
      date: { x: 50, y: 45, width: 80, height: 6, fontSize: 18, align: 'center', color: '#6b7280' },
      time: { x: 50, y: 52, width: 80, height: 5, fontSize: 16, align: 'center', color: '#6b7280' },
      location: { x: 50, y: 60, width: 80, height: 6, fontSize: 18, align: 'center', color: '#1f2937' },
    },
    defaultText: {
      title: 'TOY DƏVƏTİ',
      couple: 'Gəlin & Bəy',
    },
  },
  {
    id: 'modern-gold',
    category: 'wedding',
    name: 'Modern Gold',
    slug: 'modern-gold',
    description: 'Müasir qızıl tonlarda toy dəvəti',
    thumbnail: '/templates/modern-gold-thumb.png',
    background: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)',
    backgroundVariants: [
      'linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)',
      'linear-gradient(135deg, #2d1b69 0%, #1a1a2e 50%, #16213e 100%)',
      'linear-gradient(135deg, #1a1a2e 0%, #0f3460 100%)',
    ],
    colors: { primary: '#fbbf24', secondary: '#f59e0b', accent: '#d97706' },
    font: 'Cinzel',
    fonts: ['Cinzel', 'Playfair Display', 'Cormorant Garamond'],
    layout: 'centered-card',
    positions: {
      title: { x: 50, y: 12, width: 80, height: 8, fontSize: 28, align: 'center', color: '#fbbf24' },
      couple: { x: 50, y: 28, width: 80, height: 10, fontSize: 26, align: 'center', color: '#ffffff' },
      date: { x: 50, y: 45, width: 80, height: 6, fontSize: 18, align: 'center', color: '#d1d5db' },
      time: { x: 50, y: 52, width: 80, height: 5, fontSize: 16, align: 'center', color: '#d1d5db' },
      location: { x: 50, y: 60, width: 80, height: 6, fontSize: 18, align: 'center', color: '#ffffff' },
    },
    defaultText: {
      title: 'TOY DƏVƏTİ',
      couple: 'Gəlin & Bəy',
    },
  },
  {
    id: 'romantic-blush',
    category: 'engagement',
    name: 'Romantic Blush',
    slug: 'romantic-blush',
    description: 'Romantik çəhrayı nişan dəvəti',
    thumbnail: '/templates/romantic-blush-thumb.png',
    background: 'linear-gradient(135deg, #fff5f5 0%, #fce4ec 50%, #f8bbd0 100%)',
    backgroundVariants: [
      'linear-gradient(135deg, #fff5f5 0%, #fce4ec 50%, #f8bbd0 100%)',
      'linear-gradient(135deg, #fce4ec 0%, #f8bbd0 100%)',
      'linear-gradient(135deg, #fff5f5 0%, #f8bbd0 100%)',
    ],
    colors: { primary: '#d81b60', secondary: '#e91e63', accent: '#f48fb1' },
    font: 'Great Vibes',
    fonts: ['Great Vibes', 'Playfair Display', 'Dancing Script'],
    layout: 'centered-card',
    positions: {
      title: { x: 50, y: 15, width: 80, height: 8, fontSize: 30, align: 'center', color: '#d81b60' },
      couple: { x: 50, y: 30, width: 80, height: 8, fontSize: 22, align: 'center', color: '#4a148c' },
      date: { x: 50, y: 46, width: 80, height: 6, fontSize: 18, align: 'center', color: '#6b7280' },
      time: { x: 50, y: 53, width: 80, height: 5, fontSize: 16, align: 'center', color: '#6b7280' },
      location: { x: 50, y: 61, width: 80, height: 6, fontSize: 18, align: 'center', color: '#4a148c' },
    },
    defaultText: {
      title: 'NİŞAN DƏVƏTİ',
      couple: 'Gəlin & Bəy',
    },
  },
  {
    id: 'henna-magic',
    category: 'henna',
    name: 'Henna Magic',
    slug: 'henna-magic',
    description: 'Ənənəvi xına gecəsi dəvəti',
    thumbnail: '/templates/henna-magic-thumb.png',
    background: 'linear-gradient(135deg, #ffedd5 0%, #fed7aa 50%, #fb923c 100%)',
    backgroundVariants: [
      'linear-gradient(135deg, #ffedd5 0%, #fed7aa 50%, #fb923c 100%)',
      'linear-gradient(135deg, #fef3c7 0%, #fde68a 50%, #f59e0b 100%)',
      'linear-gradient(135deg, #ffedd5 0%, #fb923c 100%)',
    ],
    colors: { primary: '#c2410c', secondary: '#ea580c', accent: '#fdba74' },
    font: 'Playfair Display',
    fonts: ['Playfair Display', 'Georgia', 'Lora'],
    layout: 'centered-card',
    positions: {
      title: { x: 50, y: 15, width: 80, height: 8, fontSize: 28, align: 'center', color: '#c2410c' },
      hostName: { x: 50, y: 32, width: 80, height: 8, fontSize: 24, align: 'center', color: '#1f2937' },
      date: { x: 50, y: 46, width: 80, height: 6, fontSize: 18, align: 'center', color: '#6b7280' },
      time: { x: 50, y: 53, width: 80, height: 5, fontSize: 16, align: 'center', color: '#6b7280' },
      location: { x: 50, y: 61, width: 80, height: 6, fontSize: 18, align: 'center', color: '#1f2937' },
    },
    defaultText: {
      title: 'XINA GECƏSİ',
    },
  },
  {
    id: 'birthday-fun',
    category: 'birthday',
    name: 'Birthday Fun',
    slug: 'birthday-fun',
    description: 'Rəngarəng ad günü dəvəti',
    thumbnail: '/templates/birthday-fun-thumb.png',
    background: 'linear-gradient(135deg, #fce4ec 0%, #e8f5e9 50%, #fff3e0 100%)',
    backgroundVariants: [
      'linear-gradient(135deg, #fce4ec 0%, #e8f5e9 50%, #fff3e0 100%)',
      'linear-gradient(135deg, #fff3e0 0%, #fff8e1 50%, #e8f5e9 100%)',
      'linear-gradient(135deg, #e8eaf6 0%, #fce4ec 50%, #e0f2f1 100%)',
    ],
    colors: { primary: '#e91e63', secondary: '#ff9800', accent: '#ffeb3b' },
    font: 'Nunito',
    fonts: ['Nunito', 'Poppins', 'Quicksand'],
    layout: 'centered-card',
    positions: {
      title: { x: 50, y: 12, width: 80, height: 8, fontSize: 30, align: 'center', color: '#e91e63' },
      hostName: { x: 50, y: 28, width: 80, height: 8, fontSize: 24, align: 'center', color: '#1f2937' },
      date: { x: 50, y: 45, width: 80, height: 6, fontSize: 18, align: 'center', color: '#6b7280' },
      time: { x: 50, y: 52, width: 80, height: 5, fontSize: 16, align: 'center', color: '#6b7280' },
      location: { x: 50, y: 60, width: 80, height: 6, fontSize: 18, align: 'center', color: '#1f2937' },
    },
    defaultText: {
      title: 'AD GÜNÜ DƏVƏTİ',
    },
  },
  {
    id: 'baby-soft',
    category: 'baby-shower',
    name: 'Baby Soft',
    slug: 'baby-soft',
    description: 'Yumşaq pastel beşik dəvəti',
    thumbnail: '/templates/baby-soft-thumb.png',
    background: 'linear-gradient(135deg, #e0f7fa 0%, #fce4ec 50%, #f3e5f5 100%)',
    backgroundVariants: [
      'linear-gradient(135deg, #e0f7fa 0%, #fce4ec 50%, #f3e5f5 100%)',
      'linear-gradient(135deg, #e8f5e9 0%, #e0f7fa 50%, #fff3e0 100%)',
      'linear-gradient(135deg, #f3e5f5 0%, #fce4ec 100%)',
    ],
    colors: { primary: '#ec407a', secondary: '#26c6da', accent: '#ce93d8' },
    font: 'Quicksand',
    fonts: ['Quicksand', 'Nunito', 'Poppins'],
    layout: 'centered-card',
    positions: {
      title: { x: 50, y: 12, width: 80, height: 8, fontSize: 28, align: 'center', color: '#ec407a' },
      parentName: { x: 50, y: 28, width: 80, height: 8, fontSize: 22, align: 'center', color: '#1f2937' },
      babyName: { x: 50, y: 38, width: 80, height: 6, fontSize: 20, align: 'center', color: '#6b7280' },
      date: { x: 50, y: 50, width: 80, height: 6, fontSize: 18, align: 'center', color: '#6b7280' },
      time: { x: 50, y: 57, width: 80, height: 5, fontSize: 16, align: 'center', color: '#6b7280' },
      location: { x: 50, y: 65, width: 80, height: 6, fontSize: 18, align: 'center', color: '#1f2937' },
    },
    defaultText: {
      title: 'BEŞİK TOYU',
    },
  },
  {
    id: 'corporate-pro',
    category: 'corporate',
    name: 'Corporate Pro',
    slug: 'corporate-pro',
    description: 'Peşəkar korporativ dəvət',
    thumbnail: '/templates/corporate-pro-thumb.png',
    background: 'linear-gradient(135deg, #1e293b 0%, #334155 50%, #475569 100%)',
    backgroundVariants: [
      'linear-gradient(135deg, #1e293b 0%, #334155 50%, #475569 100%)',
      'linear-gradient(135deg, #0f172a 0%, #1e293b 100%)',
      'linear-gradient(135deg, #1e3a5f 0%, #2d5a8e 100%)',
    ],
    colors: { primary: '#3b82f6', secondary: '#60a5fa', accent: '#93c5fd' },
    font: 'Inter',
    fonts: ['Inter', 'Roboto', 'Poppins'],
    layout: 'centered-card',
    positions: {
      title: { x: 50, y: 12, width: 80, height: 8, fontSize: 26, align: 'center', color: '#3b82f6' },
      companyName: { x: 50, y: 26, width: 80, height: 6, fontSize: 20, align: 'center', color: '#cbd5e1' },
      eventTitle: { x: 50, y: 36, width: 80, height: 8, fontSize: 22, align: 'center', color: '#ffffff' },
      date: { x: 50, y: 50, width: 80, height: 6, fontSize: 18, align: 'center', color: '#93c5fd' },
      time: { x: 50, y: 57, width: 80, height: 5, fontSize: 16, align: 'center', color: '#93c5fd' },
      location: { x: 50, y: 65, width: 80, height: 6, fontSize: 18, align: 'center', color: '#ffffff' },
    },
    defaultText: {
      title: 'KORPORATİV TƏDBİR',
    },
  },
  {
    id: 'masterclass-vibrant',
    category: 'masterclass',
    name: 'Masterclass Vibrant',
    slug: 'masterclass-vibrant',
    description: 'Enerjili master klass dəvəti',
    thumbnail: '/templates/masterclass-vibrant-thumb.png',
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    backgroundVariants: [
      'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
      'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
      'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
    ],
    colors: { primary: '#ffffff', secondary: '#e0e7ff', accent: '#a78bfa' },
    font: 'Poppins',
    fonts: ['Poppins', 'Inter', 'Nunito'],
    layout: 'centered-card',
    positions: {
      title: { x: 50, y: 10, width: 80, height: 8, fontSize: 28, align: 'center', color: '#ffffff' },
      topic: { x: 50, y: 26, width: 80, height: 8, fontSize: 22, align: 'center', color: '#e0e7ff' },
      instructor: { x: 50, y: 38, width: 80, height: 6, fontSize: 20, align: 'center', color: '#c4b5fd' },
      date: { x: 50, y: 50, width: 80, height: 6, fontSize: 18, align: 'center', color: '#e0e7ff' },
      time: { x: 50, y: 57, width: 80, height: 5, fontSize: 16, align: 'center', color: '#e0e7ff' },
      location: { x: 50, y: 65, width: 80, height: 6, fontSize: 18, align: 'center', color: '#ffffff' },
    },
    defaultText: {
      title: 'MASTER KLASS',
    },
  },
  {
    id: 'seminar-clean',
    category: 'seminar',
    name: 'Seminar Clean',
    slug: 'seminar-clean',
    description: 'Təmiz və minimalist seminar dəvəti',
    thumbnail: '/templates/seminar-clean-thumb.png',
    background: 'linear-gradient(135deg, #f8fafc 0%, #e2e8f0 100%)',
    backgroundVariants: [
      'linear-gradient(135deg, #f8fafc 0%, #e2e8f0 100%)',
      'linear-gradient(135deg, #f1f5f9 0%, #cbd5e1 100%)',
      'linear-gradient(135deg, #ffffff 0%, #f1f5f9 100%)',
    ],
    colors: { primary: '#1e40af', secondary: '#3b82f6', accent: '#bfdbfe' },
    font: 'Inter',
    fonts: ['Inter', 'Roboto', 'Merriweather'],
    layout: 'centered-card',
    positions: {
      title: { x: 50, y: 12, width: 80, height: 8, fontSize: 28, align: 'center', color: '#1e40af' },
      topic: { x: 50, y: 28, width: 80, height: 8, fontSize: 22, align: 'center', color: '#1f2937' },
      speaker: { x: 50, y: 40, width: 80, height: 6, fontSize: 20, align: 'center', color: '#6b7280' },
      date: { x: 50, y: 52, width: 80, height: 6, fontSize: 18, align: 'center', color: '#6b7280' },
      time: { x: 50, y: 59, width: 80, height: 5, fontSize: 16, align: 'center', color: '#6b7280' },
      location: { x: 50, y: 67, width: 80, height: 6, fontSize: 18, align: 'center', color: '#1f2937' },
    },
    defaultText: {
      title: 'SEMİNAR',
    },
  },
  {
    id: 'concert-neon',
    category: 'concert',
    name: 'Concert Neon',
    slug: 'concert-neon',
    description: 'Neon işıqlı konsert dəvəti',
    thumbnail: '/templates/concert-neon-thumb.png',
    background: 'linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)',
    backgroundVariants: [
      'linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)',
      'linear-gradient(135deg, #1a0033 0%, #330066 100%)',
      'linear-gradient(135deg, #0d0d0d 0%, #1a1a2e 50%, #16213e 100%)',
    ],
    colors: { primary: '#00ff88', secondary: '#ff00e4', accent: '#7000ff' },
    font: 'Poppins',
    fonts: ['Poppins', 'Inter', 'Oswald'],
    layout: 'centered-card',
    positions: {
      title: { x: 50, y: 10, width: 80, height: 8, fontSize: 30, align: 'center', color: '#00ff88' },
      artistName: { x: 50, y: 26, width: 80, height: 8, fontSize: 26, align: 'center', color: '#ff00e4' },
      date: { x: 50, y: 44, width: 80, height: 6, fontSize: 18, align: 'center', color: '#a78bfa' },
      time: { x: 50, y: 51, width: 80, height: 5, fontSize: 16, align: 'center', color: '#a78bfa' },
      location: { x: 50, y: 60, width: 80, height: 6, fontSize: 18, align: 'center', color: '#ffffff' },
    },
    defaultText: {
      title: 'KONSERT',
    },
  },
  {
    id: 'general-party',
    category: 'general',
    name: 'General Party',
    slug: 'general-party',
    description: 'Universal tədbir dəvəti',
    thumbnail: '/templates/general-party-thumb.png',
    background: 'linear-gradient(135deg, #667eea 0%, #f5576c 100%)',
    backgroundVariants: [
      'linear-gradient(135deg, #667eea 0%, #f5576c 100%)',
      'linear-gradient(135deg, #f5576c 0%, #ff6b6b 100%)',
      'linear-gradient(135deg, #4facfe 0%, #667eea 100%)',
    ],
    colors: { primary: '#ffffff', secondary: '#f8fafc', accent: '#cbd5e1' },
    font: 'Poppins',
    fonts: ['Poppins', 'Inter', 'Nunito'],
    layout: 'centered-card',
    positions: {
      title: { x: 50, y: 10, width: 80, height: 8, fontSize: 28, align: 'center', color: '#ffffff' },
      eventTitle: { x: 50, y: 26, width: 80, height: 8, fontSize: 24, align: 'center', color: '#f8fafc' },
      hostName: { x: 50, y: 38, width: 80, height: 6, fontSize: 20, align: 'center', color: '#e2e8f0' },
      date: { x: 50, y: 50, width: 80, height: 6, fontSize: 18, align: 'center', color: '#e2e8f0' },
      time: { x: 50, y: 57, width: 80, height: 5, fontSize: 16, align: 'center', color: '#e2e8f0' },
      location: { x: 50, y: 65, width: 80, height: 6, fontSize: 18, align: 'center', color: '#ffffff' },
    },
    defaultText: {
      title: 'TƏDBİR DƏVƏTİ',
    },
  },
];

export default templates;
